#+TITLE: Beyond Two Cans and a String: A practical guide to building a router
#+AUTHOR: Ben Lewis

* Consumer routers bore me

** Background
I like to manage my equipment via command lines and SSH; it means I have a
uniform interface when dealing with machines all over the place, and I can use
it from pretty much anywhere-even my phone.

But command line interfaces just aren't common on most consumer equipment sold
today, in fact, they basically don't exist. That's a huge bummer for me, and
caused me to start looking for other options.

** Limitations
For a lot of the equipment I've found

** Goals

* Selecting hardware

** Constraints

*** RAM
    4GB of RAM is more than enough for a basic firewall; if you want to add more
    services, however, you'll want more.

*** CPU
    Any recent CPU will be powerful enough--here your concerns are cost and
    heat, mainly. Low-power embedded CPUs are great for low- or no-noise
    operation.

*** Storage
    120GB SSDs are $20 or less on Newegg; a lot of boards designed for a usecase
    like this are also built to be booted off of flash drives or SD cards.

*** NICs
    This is the heart of choosing what you'll use as a router; at a minimum, you
    need two interfaces: one external, one internal. If you've got a separate
    switch you're using for your internal network, that may be all you need; if
    you want other machines directly connected to your router, however, you'll
    need more.

** Approaches

** Considerations for expandability

* Software stack

** Axes of choice

*** Graphical/web interface
    Some options are more configurable through webpages and graphical
    environments, but are less configurable through text interfaces; careful
    configuration of interfaces and potentially a VPN may be needed to remotely
    manage some of these stacks.

*** Preference in base OS
    The mon0wall derivatives (pfSense, OPNsense) are all FreeBSD derivatives; in
    other cases, you may prefer running a Linux kernel-for familiarity's sake,
    or because of hardware support.

*** Support model

    Paid support options exist for many firewall-oriented distros and
    derivatives; generally speaking, there's also community support available,
    but you may or may not find what you need in forums, especially when dealing
    with unusual hardware or network configurations.
